apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: zc6mvtxol-python 
  janus-idp.io/tekton: zc6mvtxol-python
  backstage.io/kubernetes-id: zc6mvtxol-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: zc6mvtxol-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml