apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: zc6mvtxol-python-gitops
  description: This is GitOps manifest for zc6mvtxol-python   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: rhtap/gitops=zc6mvtxol-python
    backstage.io/kubernetes-id: zc6mvtxol-python 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: zc6mvtxol-python
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:zc6mvtxol-python
