apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: zc6mvtxol-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: zc6mvtxol-python 
  name: zc6mvtxol-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: zc6mvtxol-python 
